server: 
  port: 9001
spring:
  application:
    name: mechanician-task
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.148.211:3306/mechanician_task?useSSL=false&useUnicode=true&amp;characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  rabbitmq:
    host: 39.105.148.211
  redis:
    host: 39.105.148.211
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 0
        min-idle: 0
    timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
